# Generated by Django 4.2.3 on 2023-07-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('is_solved', models.BooleanField()),
                ('correct_answer', models.CharField(max_length=50)),
                ('user_input', models.CharField(max_length=50)),
            ],
        ),
    ]
