# Generated by Django 4.2.3 on 2023-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
