# Generated by Django 4.2.3 on 2023-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0002_alter_problem_is_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='user_input',
            field=models.CharField(default='', max_length=50),
        ),
    ]
