# Generated by Django 4.2.3 on 2023-07-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0003_alter_problem_user_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='user_input',
        ),
    ]
